route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram'
receivers:
  - name: 'telegram' 
    telegram_configs:
    - chat_id: 111222333444555
      bot_token: 123123123123123123123
      api_url: "https://api.telegram.org"
      send_resolved: true
      parse_mode: HTML
      message: '{{ template "telegram.default" . }}'